'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Wrapper from './wrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '../assets/icon.svg',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <Wrapper>
          <main className={inter.className}>{children}</main>
        </Wrapper>
      </body>
    </html>
  );
}
